### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Darkmaster006** [mansuf/mangadex-downloader#4]
```
python3 mangadex.py 
[INFO] [MAIN] Fetching "https://mangadex.org/title/14f6bd96-e062-40d6-8fd2-fc6925e54624/aoi-horus-no-hitomi-dansou-no-joou-no-monogatari"
[INFO] [FETCHER] Requesting info to mangadex main website
[INFO] [FETCHER] Checking if ip user are banned or not
[INFO] [FETCHER] Checking if given url manga is exist or not
[INFO] [FETCHER] Retrieving info from mangadex API
Traceback (most recent call last):
  File "mangadex.py", line 12, in <module>
    info = m.extract_info('https://mangadex.org/title/14f6bd96-e062-40d6-8fd2-fc6925e54624/aoi-horus-no-hitomi-dansou-no-joou-no-monogatari')
  File "/home/j/.local/lib/python3.8/site-packages/mangadex_downloader/__init__.py", line 178, in extract_info
    data = fetch.get()
  File "/home/j/.local/lib/python3.8/site-packages/mangadex_downloader/fetcher.py", line 87, in get
    r = requests.get(get_manga_api_url(manga_id))
  File "/home/j/.local/lib/python3.8/site-packages/mangadex_downloader/constants.py", line 16, in get_manga_api_url
    return BASE_API_URL + '/manga/' + manga_id + '?include=chapters'
TypeError: can only concatenate str (not "NoneType") to str
```
This is the output.

And this is my mangadex.py file:
```python
from mangadex_downloader import Mangadex

# by default, verbose is False
m = Mangadex(verbose=True)

# if you want to see all information in manga
# plus you want to download it
# do: m.extract_info('give mangadex url here')
# see example below

# this will download all chapters in manga 
info = m.extract_info('https://mangadex.org/title/14f6bd96-e062-40d6-8fd2-fc6925e54624/aoi-horus-no-hitomi-dansou-no-joou-no-monogatari')

print(info)
# Output: <MangaData title="My Tiny Senpai From Work" chapters=51 language=jp>

print(info.title)
# Output: 'My Tiny Senpai From Work'

print(info.chapters)
# Output: [{'language': 'English': 'url': ..., 'group': ..., 'uploader': ..., 'volume': ..., 'chapter': ..., 'chapter-id': ...}, ...]

# or, you want to see all information in manga
# but you don't wanna download it
# do: m.extract_info('give mangadex url here', download=False)
# see example below
```

Any help is appreciated, as I'm not that versed in Python, thanks.

**Comment by mansuf** [comment]
> Any help is appreciated, as I'm not that versed in Python, thanks.

There is no solution right now as this project is out of update and need to rework (The base codes using MangaDex v3, meanwhile the MangaDex v3 is dead and MangaDex v5 is born). I cannot guarantee that this will be fixed, because i'm busy with school right now. I will working to fix this if i have some free time.

**Comment by Darkmaster006** [comment]
> > Any help is appreciated, as I'm not that versed in Python, thanks.
> 
> There is no solution right now as this project is out of update and need to rework (The base codes using MangaDex v3, meanwhile the MangaDex v3 is dead and MangaDex v5 is born). I cannot guarantee that this will be fixed, because i'm busy with school right now. I will working to fix this if i have some free time.

Ah, I figured since the examples had the old links. No worries, then!

**Comment by mansuf** [comment]
### Update

This app has been reworked since `v0.1.0` to use MangaDex API v5, you can start update it.
