### ISSUE TITLE
FileNotFoundError when downloading PDF volumes

### ISSUE THREAD

**Issue by Ethaisa123** [mansuf/mangadex-downloader#78]
### What happened ?

After downloading the chapters when the worker converts the volume into a PDF I get a FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ethan\\Downloads\\Kobo-pine\\New Normal\\Vol. 3\\000.png

Full error below:
```
[ERROR] We have problem in queue worker
Traceback (most recent call last):
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\utils.py", line 217, in run
    job()
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 454, in <lambda>
    self.worker.submit(lambda: self.convert(self.images, file_path))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 392, in convert
    im = im_ref()
         ^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ethan\\Downloads\\Kobo-pine\\New Normal\\Vol. 3\\000.png'
[ERROR] Unhandled exception, FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ethan\\Downloads\\Kobo-pine\\New Normal\\Vol. 3\\000.png'
Traceback (most recent call last):
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\cli\__init__.py", line 76, in _main
    download(args)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\cli\download.py", line 33, in download
    url(args, args.type)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\cli\url.py", line 166, in __call__
    self.func(self.id, args)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\cli\url.py", line 97, in download_manga
    dl_manga(*args)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\main.py", line 167, in download
    download_manga(manga, base_path)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\main.py", line 137, in download_manga
    fmt.main()
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\base.py", line 697, in main
    self.download_volumes(volumes)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\base.py", line 625, in download_volumes     
    self.on_finish(file_path, volume, images)
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 454, in on_finish
    self.worker.submit(lambda: self.convert(self.images, file_path))
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\utils.py", line 196, in submit
    raise err
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\utils.py", line 217, in run
    job()
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 454, in <lambda>
    self.worker.submit(lambda: self.convert(self.images, file_path))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 392, in convert
    im = im_ref()
         ^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\mangadex_downloader\format\pdf.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ethan\\Downloads\\Kobo-pine\\New Normal\\Vol. 3\\000.png'
```

### What did you expect to happen ?

I expected the program to convert the Folders into a PDF, in the same way as the cbz method

### OS version

Windows 10

### App version

mangadex-downloader v2.10.1 (https://github.com/mansuf/mangadex-downloader)
Python: 3.11.2
arch: x64
bundled executable: no

### Installation origin

PyPI (Python Package Index)

### Reproducible command

mangadex-dl https://mangadex.org/title/e1d0056a-fdd3-4f32-af19-50eeb37280ac --save-as "pdf-volume" --use-volume-cover -uvc --progress-bar-layout=none

### Additional context

if you repeatedly do the same command over and over every time it crashes it will eventually get through all the chapters (using the download.db I'm guessing)

**Comment by mansuf** [comment]
Man, seems like i messed up when refactoring codes. Sorry about that, i've made PR #79 to fix this issue. You can test it by installing patched version.

**Please note that you need git to install patched version**

```sh
# Make sure you uninstall previous version mangadex-downloader
pip uninstall mangadex-downloader

# Install patched version
pip install -U git+https://github.com/mansuf/mangadex-downloader.git@e4b4e456ca9188d305c1af443a4c947bae570646
```

**Comment by Ethaisa123** [comment]
Oh nice works perfectly now, thanks man!

**Comment by Ethaisa123** [comment]
oh nice works perfectly now, thanks man.
