### ISSUE TITLE
Getting OS Error when using --save-as "cbz-single"

### ISSUE THREAD

**Issue by amurren** [mansuf/mangadex-downloader#8]
Version 0.6.1 on Mac OS version 12.2.1 with Python version 3.10.2

Using the --save-as "cbz-single" switch results in the error below, but using --save-as "cbz" works without an issue. I am not sure if this is an issue on my end due permissions or a missing package, or if it an issue with the app.  Thank you.

[ERROR] Unhandled exception, OSError: cannot open resource
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/cli/__init__.py", line 39, in _main
    download(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/cli/download.py", line 12, in download
    url(args, args.type)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/cli/url.py", line 89, in __call__
    self.func(self.id, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/cli/url.py", line 22, in download_manga
    dl_manga(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/main.py", line 270, in download
    fmt.main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/format/comic_book.py", line 214, in main
    mark_img = get_mark_image(chap_name, cache, index)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader/format/utils.py", line 29, in get_mark_image
    font = ImageFont.truetype(font_family, font_size)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/ImageFont.py", line 844, in truetype
    return freetype(font)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/ImageFont.py", line 841, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/ImageFont.py", line 193, in __init__
    self.font = core.getfont(
OSError: cannot open resource

**Comment by mansuf** [comment]
`cbz-single` format has additional process creating an "finished: chapter x, next: chapter x" image in end of chapter which used `arial.ttf` font.

See this example image as reference

![1_mark_image](https://user-images.githubusercontent.com/43638783/158206355-526a5b47-eff2-41ad-b2e0-38e281a1d21a.png)

As i looked so far, your OS seems doesn't have `arial.ttf` font. Maybe check your installed fonts maybe ?
