### ISSUE TITLE
AttributeError (unhandled exception) attempting to download specific manga

### ISSUE THREAD

**Issue by curtvdh** [mansuf/mangadex-downloader#92]
### What happened ?

Downloading this title results in a stack trace ending with AttributeError: 'NoneType' object has no attribute 'name':

https://mangadex.org/title/d703e15b-8bfb-4fc1-a8fe-1d8fb8626ef1/puku-yuri

### What did you expect to happen ?

Manga should be downloaded.

### OS version

Ubuntu 22.10

### App version

v2.10.3

### Installation origin

PyPI (Python Package Index)

### Reproducible command

mangadex-dl https://mangadex.org/title/d703e15b-8bfb-4fc1-a8fe-1d8fb8626ef1/puku-yuri --save-as pdf-single

### Additional context

Stack trace:

Traceback (most recent call last):
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/cli/__init__.py", line 76, in _main
    download(args)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/cli/download.py", line 33, in download
    url(args, args.type)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/cli/url.py", line 166, in __call__
    self.func(self.id, args)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/cli/url.py", line 97, in download_manga
    dl_manga(*args)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/main.py", line 167, in download
    download_manga(manga, base_path)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/main.py", line 137, in download_manga
    fmt.main()
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/format/base.py", line 830, in main
    self.download_single(total, merged_name, cache)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/format/base.py", line 780, in download_single
    ims = self.get_images(chap_class, chap_images, path, count)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/format/base.py", line 87, in get_images
    chap_name = chap_class.get_name()
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/chapter.py", line 302, in get_name
    return self._make_name(self._name)
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/chapter.py", line 290, in _make_name
    name += f'[{sanitize_filename(self.groups_name)}] '
  File "/home/curt/py3_venv/lib/python3.10/site-packages/mangadex_downloader/chapter.py", line 311, in groups_name
    return f'User - {self.user.name}'
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by mansuf** [comment]
This bug has been fixed in #93. You can try it yourself by installing development version. If you have problem or another issue, let me know 👍

If you have git, you can install it with pip.

```
pip uninstall mangadex-downloader
pip install git+https://github.com/mansuf/mangadex-downloader.git@26fa397b98402e879af29497df961206d4652acc
```

If you're installing mangadex-downloader from github releases, you can download the development version in here:

The download files are available in "artifacts" section

https://github.com/mansuf/mangadex-downloader/actions/runs/7257051033
